import streamlit as st

TEXTOS = {
    "titulo_app": "Sistema de Cálculo de Custos de Produção",
    "gerenciar_producao_titulo": "Gerenciar Produtos e Variáveis",
    "adicionar_produto_titulo": "Adicionar Novo Produto",
    "nome_produto_label": "Nome do Produto",
    "descricao_produto_label": "Descrição do Produto",
    "unidade_medida_label": "Unidade de Medida (ex: kg, un, m)",
    "formula_produto_label": "Fórmula de Cálculo (ex: variavel1 + variavel2 * 2)",
    "categoria_label": "Categoria",  # Manter esta para compatibilidade temporária
    "adicionar_variavel_titulo": "Adicionar Nova Variável",
    "nome_variavel_label": "Nome da Variável",
    "custo_variavel_label": "Custo da Variável",
    "salvar_produto_btn": "Salvar Produto",
    "salvar_variavel_btn": "Salvar Variável",
    "produtos_existentes_titulo": "Produtos Existentes",
    "variaveis_existentes_titulo": "Variáveis Existentes",
    "editar_produto_btn": "Editar",
    "excluir_produto_btn": "Excluir",
    "editar_variavel_btn": "Editar",
    "excluir_variavel_btn": "Excluir",
    "selecione_produto_calcular": "Selecione um produto para calcular o custo:",
    "calcular_custo_btn": "Calcular Custo",
    "custo_calculado": "Custo Calculado:",
    "erro_generico": "Ocorreu um erro. Por favor, tente novamente.",
    "erro_formula_invalida": "Erro na fórmula. Verifique a sintaxe e as variáveis.",
    "produto_salvo_sucesso": "Produto salvo com sucesso!",
    "variavel_salva_sucesso": "Variável salva com sucesso!",
    "produto_excluido_sucesso": "Produto excluído com sucesso!",
    "variavel_excluida_sucesso": "Variável excluída com sucesso!",
    "erro_salvar_produto": "Erro ao salvar produto.",
    "erro_salvar_variavel": "Erro ao salvar variável.",
    "erro_excluir_produto": "Erro ao excluir produto.",
    "erro_excluir_variavel": "Erro ao excluir variável.",
    "erro_carregar_dados": "Erro ao carregar dados do banco de dados.",
    "erro_conexao_db": "Erro de conexão com o banco de dados. Verifique suas credenciais.",
    "nenhum_produto_encontrado": "Nenhum produto encontrado.",
    "nenhuma_variavel_encontrada": "Nenhuma variável encontrada.",
    "confirmar_exclusao_produto": "Tem certeza que deseja excluir este produto?",
    "confirmar_exclusao_variavel": "Tem certeza que deseja excluir esta variável?",
    "gerenciar_categorias_titulo": "Gerenciar Categorias",
    "adicionar_categoria_btn": "Adicionar Categoria",
    "nova_categoria_label": "Nova Categoria",
    "categoria_salva_sucesso": "Categoria salva com sucesso!",
    "erro_salvar_categoria": "Erro ao salvar categoria.",
    "categorias_existentes_titulo": "Categorias Existentes",
    "excluir_categoria_btn": "Excluir",
    "confirmar_exclusao_categoria": "Tem certeza que deseja excluir esta categoria?",
    "erro_excluir_categoria": "Erro ao excluir categoria.",
    "categoria_em_uso": "Não é possível excluir a categoria, pois está em uso por produtos ou variáveis.",
    "nenhuma_categoria_encontrada": "Nenhuma categoria encontrada.",
    "categorias_produtos_titulo": "Categorias de Produtos",
    "categorias_variaveis_titulo": "Categorias de Variáveis",
    "adicionar_categoria_produto_btn": "Adicionar Categoria de Produto",
    "adicionar_categoria_variavel_btn": "Adicionar Categoria de Variável",
    "nova_categoria_produto_label": "Nova Categoria de Produto",
    "nova_categoria_variavel_label": "Nova Categoria de Variável",
    "categoria_produto_salva_sucesso": "Categoria de produto salva com sucesso!",
    "categoria_variavel_salva_sucesso": "Categoria de variável salva com sucesso!",
    "erro_salvar_categoria_produto": "Erro ao salvar categoria de produto.",
    "erro_salvar_categoria_variavel": "Erro ao salvar categoria de variável.",
    "excluir_categoria_produto_btn": "Excluir Categoria de Produto",
    "excluir_categoria_variavel_btn": "Excluir Categoria de Variável",
    "confirmar_exclusao_categoria_produto": "Tem certeza que deseja excluir esta categoria de produto?",
    "confirmar_exclusao_categoria_variavel": "Tem certeza que deseja excluir esta categoria de variável?",
    "erro_excluir_categoria_produto": "Erro ao excluir categoria de produto.",
    "erro_excluir_categoria_variavel": "Erro ao excluir categoria de variável.",
    "categoria_produto_em_uso": "Não é possível excluir a categoria de produto, pois está em uso por produtos.",
    "categoria_variavel_em_uso": "Não é possível excluir a categoria de variável, pois está em uso por variáveis.",
    "categoria_produto_label": "Categoria do Produto",
    "categoria_variavel_label": "Categoria da Variável"
}
